[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.vim/rc/plugins/quickrun.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_guide_size = 1
  let g:indent_guides_space_guides = 1
  let g:indent_guides_exclude_filetypes = ['help', 'vimfiler', 'unite']
'''
hook_add = '''
  augroup MyAutoCmd
    autocmd Colorscheme * :hi IndentGuidesOdd ctermbg=black
    autocmd Colorscheme * :hi IndentGuidesEven ctermbg=darkgrey
  augroup END
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <Leader>gs :<C-u>Gstatus<Enter>
  nnoremap <Leader>gb :<C-u>Gblame<Enter>
'''

[[plugins]]
repo = 'cohama/agit.vim'
hook_add = '''
  nnoremap <Leader>ag :Agit<Enter>
'''

# Resize window
[[plugins]]
repo = 'jimsei/winresizer'
hook_source = '''
  let g:winresizer_enable = 1
  let g:winresizer_start_key = '<C-E>'
'''

# themes
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:airline_theme = 'molokai'
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#left_sep = ' '
  let g:airline#extensions#tabline#left_alt_sep = '|'

  nnoremap <silent> <C-t><C-l> :bnext<Enter>
  nnoremap <silent> <C-t><C-h> :bprevious<Enter>
  nnoremap <silent> <C-t><C-a> :bfirst<Enter>
  nnoremap <silent> <C-t><C-e> :blast<Enter>
  nnoremap <silent> <C-t><C-k> :bd<Enter>
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'joedicastro/vim-molokai256'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  " 行頭にコメントをトグル
  nmap <Leader>c <Plug>(caw:zeropos:toggle)
  vmap <Leader>c <Plug>(caw:zeropos:toggle)
'''

