[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
build = ':UpdateRemotePlugins'
hook_source = 'source ~/.vim/dein/plugins/denite.vim'
hook_add = '''
  nnoremap <silent> <Leader>fg :<C-u>Denite file_rec -highlight-mode-insert=PmenuSel<CR>
  nnoremap <silent> <Leader>g :<C-u>Denite grep -no-empty -highlight-mode-insert=PmenuSel<CR>
  nnoremap <silent> <Leader>gw :<C-u>DeniteCursorWord grep -no-empty -highlight-mode-insert=PmenuSel<CR>
'''

[[plugins]]
repo = 'Shougo/unite.vim'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
build = ':UpdateRemotePlugins'
if = "has('nvim')"
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_start_length = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-m> <Plug>(neosnippet_expand_or_jump)
  smap <C-m> <Plug>(neosnippet_expand_or_jump)
  xmap <C-m> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_ft = ['vim', 'html', 'toml']
hook_add = '''
 let g:precious_enable_switch_CursorMoved = { '*': 0, 'help': 1 }
 autocmd MyAutoCmd InsertEnter * :PreciousSwitch
 autocmd MyAutoCmd InsertLeave * :PreciousReset"}
'''

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_i = 1
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/dein/plugins/neocomplete.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_add = '''
  nnoremap <silent> <Leader>ff :<C-u>VimFiler -invisible<CR>
  noremap <silent> <Leader>ex :VimFilerExplorer<CR>
  autocmd FileType vimfiler nmap <buffer> <CR> <Plug>(vimfiler_expand_or_edit)
'''

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = {n = '<Plug>'}
on_if = "!has('nvim')"
hook_add = '''
  nnoremap <silent> <Leader>sh :VimShell<CR>
  nnoremap <silent> <Leader>sc :VimShellClos<CR>
'''

# Auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# completion
[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = 'deoplete.nvim'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
depends = 'deoplete.nvim'
on_ft = 'go'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
depends = 'deoplete.nvim'
on_ft = 'ruby'
hook_source = '''
  let g:deoplete#sources#omni#input_patterns = {
  \   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
hook_source = '''
  autocmd MyAutoCmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'tweekmonster/impsort.vim'
on_cmd = 'ImpSort'
on_ft = 'python'
hook_source = 'let g:impsort_highlight_imported = 0'

