[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = 'source ~/.vim/dein/plugins/denite.vim'
hook_add = '''
  nnoremap <silent> <Leader>dr
    \ :<C-u>Denite -buffer-name=register
    \ register neoyank<CR>
  xnoremap <silent> <Leader>gr
    \ :<C-u>Denite -default-action=replace -buffer-name=register
    \ register neoyank<CR>

  nnoremap <silent> <Leader>d<Space>
    \ :<C-u>Denite file_rec<CR>

  nnoremap <silent> ;g :<C-u>DeniteCursorWord grep<CR>
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_i = 1
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
  source ~/.vim/dein/plugins/neocomplete.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = {n = '<Plug>'}
on_if = "isdirectory(bufname('%'))"
hook_add = '''
  nnoremap <silent> <Leader>ff :<C-u>VimFiler -invisible<CR>
  noremap <silent> <Leader>ex :VimFilerExplorer<CR>
  autocmd FileType vimfiler nmap <buffer> <CR> <Plug>(vimfiler_expand_or_edit)
'''

[[plugins]]
repo = 'Shougo/vimshell.vim'
on_map = {n = '<Plug>'}
on_if = "!has('nvim')"
hook_add = '''
  nnoremap <silent> <Leader>sh :VimShell<CR>
  nnoremap <silent> <Leader>sc :VimShellClos<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
on_ft = 'go'

[[plugins]]
repo = 'fatih/vim-go'
on_i = 1
on_ft = 'go'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_i = 1
on_ft = 'ruby'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'
hook_source = '''
  autocmd MyAutoCmd FileType java setlocal omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'tweekmonster/impsort.vim'
on_cmd = 'ImpSort'
hook_source = 'let g:impsort_highlight_imported = 0'

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
depends = ['vimproc.vim']
hook_source = '''
  let g:monster#completion#rcodetools#backend = "async_rct_complete"
'''
